{
  "openapi": "3.0.0",
  "info": {
    "title": "Sample API",
    "version": "1.0.0"
  },
  "paths": {
    "/users": {
      "get": {
        "summary": "Get all users"
      },
      "post": {
        "summary": "Create a new user"
      }
    },
    "/users/{userId}": {
      "get": {
        "summary": "Get user by ID"
      },
      "put": {
        "summary": "Update user"
      },
      "delete": {
        "summary": "Delete user"
      }
    },
    "/users/{userId}/posts": {
      "get": {
        "summary": "Get posts for a user"
      }
    }
  }
}
